version: "2"

services:
  test:
    build: .
    volumes:
      - "$HOME/.ssh:/tmp/host-ssh"
      - "$PWD:/app"
    networks:
      - internal
    links:
      - postgres
    environment:
      DB_NAME: gate_goat-pg-test
      MIX_ENV: test
    command: ["mix", "test"]

  postgres:
    image: postgres:9.4
    container_name: gate_goat-pg-test
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    networks:
      - internal
       # Mapping internal PG ports so that we can access it in the host via pgAdmin etc.
#    ports:
#      - "5432:5432"


networks:
  internal:
